production:
  BASE_URL: ''
  SMTP_SETTING_ADDRESS: ''
  SMTP_SETTING_PORT: ''
  SMTP_SETTING_USERNAME: ''
  SMTP_SETTING_PASSWORD: ''
  MAILER_SENDER: ''
development:
  BASE_URL: ''
  SMTP_SETTING_ADDRESS: ''
  SMTP_SETTING_PORT: ''
  SMTP_SETTING_USERNAME: ''
  SMTP_SETTING_PASSWORD: ''
  MAILER_SENDER: ''
test:
  BASE_URL: ''
  SMTP_SETTING_ADDRESS: ''
  SMTP_SETTING_PORT: ''
  SMTP_SETTING_USERNAME: ''
  SMTP_SETTING_PASSWORD: ''
  MAILER_SENDER: 'test@test.com'